<?php
	$tracyVersion = defined("\\Tracy\\Debugger::Version")
		? \Tracy\Debugger::Version
		: \Tracy\Debugger::VERSION;
	$nonce = version_compare($tracyVersion, '2.10.8', '>=')
		? \Tracy\Helpers::getNonceAttr()
		: \Tracy\Helpers::getNonce();
	$nonceAttr = $nonce ? ' nonce="' . \Tracy\Helpers::escapeHtml($nonce) . '"' : '';
?><style type="text/css"<?php echo $nonceAttr; ?>><?php
	include_once(__DIR__ . '/session.panel.css');
?></style>
<div class="tracy-panel-session">
	<h1>
		<span class="left">Session</span>
		<?php if ($this->sessionMaxLifeTime): ?>
			<span class="right">Max. life time: <?php echo $this->sessionMaxLifeTime; ?></span>
		<?php endif; ?>
	</h1>
	<div id="tracy-panel-session-content">
		<?php
			foreach ($this->session as & $item):
				$itemNamespaceType = $item->type == self::_TYPE_NAMESPACE;
		?><table><thead><tr><th>
			<div class="namespace"><?php echo $item->key; ?></div>
			<div class="metainfo">
				<i class="type"><?php
					echo 'Record type: ';
					echo ($itemNamespaceType) ? 'Session namespace' : 'PHP value';
				?></i><?php if ($itemNamespaceType && count($item->expirations) > 0): ?>,
				<i class="expiration">Expiration after: <?php
					$glue = '';
					foreach ($item->expirations as $expiration) {
						echo $glue . $expiration->text;
						$glue = ', ';
					}
				?></i><?php endif; ?>
			</div>
		</th></tr></thead><tbody><tr><td><?php 
			echo $item->value;
		?></td></tr></tbody></table>
	<?php endforeach; ?></div>
	<?php echo $this->_debugCode; ?>
</div>