<style type="text/css">
	#tracy-session-panel{overflow:hidden;}
	.tracy-mode-float #tracy-session-panel{overflow:visible;}
	#tracy-session-panel h1{cursor:move;overflow:hidden;}
	#tracy-debug #tracy-session-panel h1{padding-right:0;}
	#tracy-session-panel h1 *{white-space:nowrap;}
	#tracy-session-panel h1 .left{display:block;float:left;line-height:30px;font-size:24px;}
	#tracy-session-panel h1 .right{display:block;float:right;line-height:16px;font-size:10px;padding-top:12px;}
	#tracy-session-panel .content{width:100%;display:table;}
	#tracy-session-panel .content table{width:100%;border-collapse:collapse;background:#FDF5CE;margin:0 0 5px 0;}
	#tracy-session-panel .content div.namespace{line-height:1.3em;font-size:14px;}
	#tracy-session-panel .content .metainfo{color:#aaa;white-space:nowrap;font-weight:normal;line-height:1.25em;font-size:10px;}
	#tracy-session-panel .content .metainfo i{display:inline-block;}
	#tracy-session-panel .content .metainfo i.expiration{margin-left:20px;}
	#tracy-session-panel .content table td,
	#tracy-session-panel .content table th{border:1px solid #E6DFBF;padding:2px 5px;vertical-align:top;text-align:left;}
</style>
<div id="tracy-session-panel">
	<h1>
		<span class="left">Session</span>
		<?php if ($this->sessionMaxLifeTime): ?>
			<span class="right">Max. life time: <?php echo $this->sessionMaxLifeTime; ?></span>
		<?php endif; ?>
	</h1>
	<div class="content">
		<?php
			foreach ($this->session as & $item):
				$itemNamespaceType = $item->type == self::_TYPE_NAMESPACE;
		?><table><thead><tr><th>
			<div class="namespace"><?php echo $item->key; ?></div>
			<div class="metainfo">
				<i class="type"><?php
					echo 'Record type: ';
					echo ($itemNamespaceType) ? 'Session namespace' : 'PHP value';
				?></i><?php if ($itemNamespaceType && count($item->expirations) > 0): ?>,
				<i class="expiration">Expiration after: <?php
					$glue = '';
					foreach ($item->expirations as $expiration) {
						echo $glue . $expiration->text;
						$glue = ', ';
					}
				?></i><?php endif; ?>
			</div>
		</th></tr></thead><tbody><tr><td><?php 
			echo $item->value;
		?></td></tr></tbody></table>
	<?php endforeach; ?></div>
	<?php echo $this->_debugCode; ?>
</div>